locallibrary/catalog/urls.py
from django.urls import re_path
from . import views


urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^books/$', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    re_path(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    re_path(r'^book/(?P<pk>[-\w]+)/renew/$', views.renew_book_librarian, name='renew-book-librarian'),
    re_path(r'^borrowed/$', views.BorrowedBooksListView.as_view(), name='all-borrowed'),
    re_path(r'^author/create/$', views.AuthorCreate.as_view(), name='author-create'),
    re_path(r'^author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(), name='author-update'),
    re_path(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(), name='author-delete'),
    re_path(r'^book/create/$', views.BookCreate.as_view(), name='book-create'),
    re_path(r'^book/(?P<pk>\d+)/update/$', views.BookUpdate.as_view(), name='book-update'),
    re_path(r'^book/(?P<pk>\d+)/delete/$', views.BookDelete.as_view(), name='book-delete'),
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
path('admin/', admin.site.urls),
path('catalog/', include('catalog.urls')),
path('',RedirectView.as_view(url='/catalog/', permanent=True)),
path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
import uuid
import datetime
from django.core.exceptions import ValidationError




class Genre(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction,"
                                                      "French Poerty etc.)")

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    def display_genre(self):
        return ','.join([ genre.name for genre in self.genre.all()[:3]])
    display_genre.short_description = 'Genre'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across the whole library")

    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved')
    )

    borrower = models.ForeignKey(User,on_delete=models.SET_NULL, null=True, blank=True)
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m',
                              help_text="Book availability")

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return f'{self.book.title} (ID: {self.id}) - Status: {self.get_status_display()}, Due back: {self.due_back if self.due_back else "No due date"}'



class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(null=True, blank=True)

    def clean(self):
        if self.date_of_birth and (datetime.date.today() - self.date_of_birth).days < 18 * 365:
            raise ValidationError({'date_of_birth': ('Автор должен быть старже 18 лет.')})

        if self.date_of_death and self.date_of_death >= datetime.date.today():
            raise ValidationError({'date_of_death': ('Дата смерти не может быть позднее чем вчера.')})

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

locallibrary/catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime #for checking renewal date range.

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Введите дату не более 4 недель (автоматически 3)")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data

locallibrary/catalog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Book, Author, BookInstance, Genre
from django.views import generic
from django.http import Http404, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView
import datetime
from .forms import RenewBookForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView


class BookCreate(CreateView):
    model = Book
    fields = '__all__'

class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')

class AuthorCreate(CreateView):
    model = Author
    fields ='__all__'
    initial={'date_of_death':'12.10.2016'}

class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name','last_name','date_of_birth','date_of_death']

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')


class BorrowedBooksListView(PermissionRequiredMixin, ListView):
    model = BookInstance
    template_name = 'catalog/borrowed_books_list.html'
    context_name = 'all-borrowed'
    permission_required = 'catalog.can_mark_returned'

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request,pk):
    book_inst = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':
        form = RenewBookForm(request.POST)

        if form.is_valid():
           book_inst.due_back = form.cleaned_data['renewal_date']
           book_inst.save()

        return HttpResponseRedirect(reverse('all-borrowed'))

    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks = 3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})

    return render(request,'catalog/book_renew_librarian.html',{'form':form, 'bookinst':book_inst})

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 2

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

class AuthorListView(generic.ListView):
    model = Author

    def get_context_data(self, **kwargs):
        context = super(AuthorListView, self).get_context_data(**kwargs)
        return context

class AuthorDetailView(generic.DetailView):
    model = Author
    paginate_by = 2

    def author_detail_view(request, pk):
        try:

            author_id = Author.objects.get(pk=pk)
        except Author.DoesNotExist:
            raise Http404("Author does not exist")

        return render (
            request,
            'catalog/author_detail.html',
            context={"author": author_id}
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['books'] = Book.objects.filter(author=self.object)
        return context

class BookListView(generic.ListView):
    model = Book
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context['some_data'] = 'This is just some data'
        return context

class BookDetailView(generic.DetailView):
    model = Book

    def book_detail_view(request, pk):
        try:
            book_id = Book.objects.get(pk=pk)
        except Book.DoesNotExist:
            raise Http404("Book does not exist")


        return render(
            request,
            'catalog/book_detail.html',
            context={'book':book_id}
        )


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    search_word =  request.GET.get('search_word', '')
    search_word_lower = search_word.lower()

    if search_word:
        book_count = Book.objects.filter(title__icontains=search_word_lower).count()
    else:
        book_count = 0

    return render (
        request,
        'index.html',
        context=
        {'num_books':num_books,'num_instances':num_instances, 'num_instances_available':num_instances_available,
         'num_authors':num_authors, 'search_word':search_word, 'book_count':book_count, 'num_visits':num_visits},
    )

locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Удаление автора</h1>

  <p>Вы действительно хотите удалить автора?: {{ author }}?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete." />
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Автор: {{ author }}</h1>

  <p>Родился: {{ author.date_of_birth }}</p>

  <h3>Книги написанные данным автором</h3>
  <ul>
    {% for book in books %}
      <li>
        <a href="{% url 'book-detail' book.pk %}">{{ book.title }} {{ book }}</a>
      </li>
    <p>{{ book.summary }}</p>
    {% empty %}
      <li>Автор не имеет книг</li>
    {% endfor %}
  </ul>
  {% if request.user.is_staff %}
                    {% csrf_token %}
    <a class="author-deletes" href="{% url 'author-delete' author.id %}">Удалить автора</a>
{% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/author_form.html
    {% extends "base_generic.html" %}

    {% block content %}
    <div class="author-forms">
      <form action="" method="post">
          {% csrf_token %}
          <table>
          {{ form.as_table }}
          </table>
          <input type="submit" value="Submit" />
      </form>
    </div>
    {% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список авторов</h1>

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author }} ({{ author.date_of_birth }}) </a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>Авторов нет</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/author_manage.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Управление авторами</h1>
  <ul>
    {% for author in object_list %}
      <li>
        {{ author.first_name }} {{ author.last_name }}

        <a href="{% url 'author-delete' author.id %}">Удалить</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

locallibrary/catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Удаление книги</h1>

  <p>Вы действительно хотите удалить книгу?: {{ book.title }}?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Да, удалить." />
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Название: {{ book.title }}</h1>
  <p>
  <strong>Автор:</strong>
    {% if author %}
  <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a>
    {% else %}
<p>Автор не указан</p>
{% endif %}
</p>
  <p><strong>Краткое содержание:</strong> {{ book.summary }}</p>
  <p><strong>Книжный номер:</strong> {{ book.isbn }}</p>
<!--  <p><strong>Язык:</strong> {{ book.language }}</p>-->
  <p><strong>Жанр:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div>
    <h4>Копии</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Вернуть:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Напечатаны:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Идентификатор:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
  {% if request.user.is_staff %}
                    {% csrf_token %}
    <a class="book-deletes" href="{% url 'book-delete' book.id %}">Удалить книгу</a>
{% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}
<div class="book-forms">
  <form action="" method="post">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Submit" />
  </form>
</div>
{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список книг</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> {% if book.author %} ({{book.author}})
          {% else %}
          <p>(Автор не указан)</p>
          {% endif %}
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>Книг нет в библиотеке</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_manage.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Управление Книгами</h1>
  <ul>
    {% for book in object_list %}
      <li>
        {{ book.title }}

        <a href="{% url 'book-delete' book.id %}">Удалить</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

locallibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Продлить: {{bookinst.book.title}}</h1>
    <p>Взято: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Дата: {{bookinst.due_back}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_librarian.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Взятые книги</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Взятых книг нет.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/borrowed_books_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Все взятые книги</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) {% if user.is_staff %}- {{ bookinst.borrower }}{% endif %} {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Продлить</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>Книги не взяты.</p>
    {% endif %}
{% endblock %}